#!/bin/bash

set -e

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "=> installing package"
dpkg -i /tmp/streamy_1.0_armhf.deb

echo "=> installing service"
cp -r /apps/streamy/service/etc/* /etc
update-rc.d streamy defaults

echo "=> restarting streamy"
service streamy restart
