#!/bin/bash

set -e

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

user="pi"

echo "Starting pulseaudio"
su $user -c "pulseaudio --start"
su $user -c "amixer -c 0 cset numid=3 1"

reset() {
    echo "Resetting the bluetooth radio"
    service bluetooth restart
    sleep 5

    echo "Reconfiguring and setting bluetooth to visible"
    hciconfig hci0 up
    hciconfig hci0 noscan
    hciconfig hci0 name "Streamy Speakers"
    hciconfig hci0 class 0x200414
    hciconfig hci0 piscan
}

echo "Starting the bluetooth agent"

reset

sudo -u $user bluetooth-agent 0000 &
sudo -u $user /apps/streamy/service/streamy-py
